/* إعدادات الطلب — يجب ضبط السعر ورابط استقبال الطلبات قبل الإطلاق */ 
const CONFIG = {
  PRODUCT_NAME: "Googeer Himalayan Shilajit",
  PRODUCT_WEIGHT: "100 غرام",
  PRODUCT_PRICE_SAR: null,
  // ضع رابط endpoint آمن يستقبل طلبات checkout (مثل Google Apps Script Web App أو backend متجرك).
  // لا تضع أسرارًا أو مفاتيح خاصة في هذا الملف العام.
  ORDER_ENDPOINT: "",
  SNAP_PIXEL_ID: "233915bf-25f6-4119-9362-701fe3212185"
};
(function initPixel(){if(!CONFIG.SNAP_PIXEL_ID)return;try{(function(e,t,n){if(e.snaptr)return;const a=e.snaptr=function(){a.handleRequest?a.handleRequest.apply(a,arguments):a.queue.push(arguments)};a.queue=[];const r=t.createElement("script");r.async=true;r.src=n;const s=t.getElementsByTagName("script")[0];s.parentNode.insertBefore(r,s)})(window,document,"https://sc-static.net/scevent.min.js");window.snaptr("init",CONFIG.SNAP_PIXEL_ID);window.snaptr("track","PAGE_VIEW",{item_category:"dietary_supplement"});}catch(_){} })();
const money = value => Number.isFinite(value)&&value>0 ? new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR",maximumFractionDigits:2}).format(value) : "يُحدد من الإعدادات";
const unit=document.getElementById("unit-price"),total=document.getElementById("summary-total"),mobile=document.getElementById("mobile-price"),qty=document.getElementById("quantity"),summaryQty=document.getElementById("summary-qty");
function updateTotals(){const q=Number(qty?.value||1);if(unit)unit.textContent=money(CONFIG.PRODUCT_PRICE_SAR);if(total)total.textContent=Number.isFinite(CONFIG.PRODUCT_PRICE_SAR)&&CONFIG.PRODUCT_PRICE_SAR>0?money(CONFIG.PRODUCT_PRICE_SAR*q):"يُحدد من الإعدادات";if(mobile)mobile.textContent=money(CONFIG.PRODUCT_PRICE_SAR);if(summaryQty)summaryQty.textContent=String(q);}
qty?.addEventListener("change",updateTotals);updateTotals();
const form=document.getElementById("order-form"),status=document.getElementById("form-status");
form?.addEventListener("submit",async event=>{event.preventDefault();if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form).entries());data.product=CONFIG.PRODUCT_NAME;data.weight=CONFIG.PRODUCT_WEIGHT;data.quantity=Number(data.quantity);data.unit_price_sar=Number.isFinite(CONFIG.PRODUCT_PRICE_SAR)&&CONFIG.PRODUCT_PRICE_SAR>0?CONFIG.PRODUCT_PRICE_SAR:null;data.total_sar=data.unit_price_sar?data.unit_price_sar*data.quantity:null;data.currency="SAR";data.payment_method="COD";data.page_url=location.href;data.submitted_at=new Date().toISOString();if(!CONFIG.ORDER_ENDPOINT || !Number.isFinite(CONFIG.PRODUCT_PRICE_SAR) || CONFIG.PRODUCT_PRICE_SAR<=0){status.className="form-status error";status.textContent="نعتذر، الطلب الإلكتروني غير متاح مؤقتًا. لم يتم تسجيل طلبك؛ يرجى المحاولة لاحقًا.";return;}const button=form.querySelector("button[type=submit]");button.disabled=true;button.textContent="جارٍ إرسال الطلب…";status.className="form-status";status.textContent="جارٍ إرسال بيانات الطلب…";try{const response=await fetch(CONFIG.ORDER_ENDPOINT,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(data),redirect:"follow"});if(!response.ok)throw new Error("Request failed");let result={};try{result=await response.json()}catch(_){}if(result.success!==true)throw new Error("Order not explicitly confirmed by endpoint");status.className="form-status success";status.textContent="تم استلام طلبك بنجاح. سيتواصل معك الفريق لتأكيد تفاصيل التوصيل.";try{if(typeof window.snaptr==="function" && Number(data.total_sar)>0)window.snaptr("track","PURCHASE",{price:data.total_sar,currency:"SAR",item_ids:["GOOGEER-SHILAJIT-100G"]});}catch(_){}form.reset();updateTotals();}catch(_){status.className="form-status error";status.textContent="تعذر إرسال الطلب الآن. لم يتم تسجيل الطلب؛ حاول مرة أخرى لاحقًا."; }finally{button.disabled=false;button.innerHTML="إرسال طلب الدفع عند الاستلام <span>←</span>";}});
document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener("click",event=>{const target=document.getElementById(link.getAttribute("href").slice(1));if(!target)return;event.preventDefault();target.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"});}));
